---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Cluster tables

```{r}
table(memberships_CPM)
table(clusters_WGCNA)
```


```{r}
library(textshape)
library(pheatmap)
library(UniProt.ws)
library(enrichR)
```

# Match Clusters (Jaccard index)

```{r}
jaccard <- function(a, b) {
    union <- length(a) + length(b) - length(intersect(a, b))
    return ((length(intersect(a, b)))/union)
}

matching_clust_num <- min(length(rownames(table(clusters_WGCNA))) - 1,
                          length(rownames(table(memberships_CPM))) - 1)

indices <- c()
matches <- c()
for (i in rownames(table(memberships_CPM))) {
  for (j in rownames(table(clusters_WGCNA))) {
    members_CPM <- rownames(cor_df)[memberships_CPM$memberships_CPM == i]
    members_WGCNA <- rownames(df_WGCNA)[clusters_WGCNA == j]
    # Calculate Jaccard index
    j_index <- jaccard(members_CPM, members_WGCNA)
    indices <- c(indices, j_index)
    matches <- c(matches, paste(i,j))
  }
}

# Best matching cluster
clusts <- strsplit(matches[which.max(indices)], " ")[[1]]
CPM_proteins <- rownames(cor_df)[memberships_CPM$memberships_CPM == clusts[1]]
WGCNA_proteins <- rownames(df_WGCNA)[clusters_WGCNA == clusts[2]]
inter_mem <- intersect(CPM_proteins, WGCNA_proteins)
length(inter_mem)

# Map to Gene names
up <- UniProt.ws(taxId = 9606)
res <- select(
    x = up,
    keys = inter_mem,
    to = "Gene_Name"
)

# List of databases: View(listEnrichrDbs())
dbs <- c("WikiPathway_2023_Human", "GO_Biological_Process_2023", "KEGG_2021_Human")
enriched <- enrichr(res$To, dbs)
plotEnrich(enriched[[3]], showTerms = 10, numChar = 40, y = "Ratio",
           orderBy = "P.value")
```

# Analyze Clusters

```{r}
enrichment <- 1
enriched_genes <- strsplit(enriched[[3]][enrichment, "Genes"], ";")[[1]]

# View(enriched_WGCNA[[3]])
enriched_genes
enriched_prots <- c()
for (i in 1:length(res$To)) {
  if (res$To[i] %in% mems) {
    enriched_prots <- c(enriched_prots,(res$From[i]))
  }
}

temp_df <- cor_df[enriched_prots, enriched_prots]
pheatmap(temp_df,
         color = colorRampPalette(c("#4d72af", "white", "#c44e53")) (101),
         breaks = seq(from = -1, to = 1, length.out = 101),
         border_color = NA,legend = FALSE, show_colnames = FALSE,
         show_rownames = TRUE,
         cluster_rows = FALSE, cluster_cols = FALSE,
         cellwidth = 550/nrow(temp_df), cellheight = 550/nrow(temp_df),
         fontfamily = 'sans', fontsize = 10,
         display_numbers = round(temp_df, 2))
```

