---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Import

```{r}
library(scp)
library(scpdata)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(textshape)
library(Hmisc)
```

# Load Data

```{r}
scp <- specht2019v3() # Load data set
scp <- aggregateFeaturesOverAssays(scp, i = "peptides", fcol = "protein", 
                                    name = "proteins_NA", fun = colMedians,
                                    na.rm = TRUE)
```

# Cell Type + Batch

```{r}
# Subset same type of cells
scp_sub <- getWithColData(scp, "proteins")
scp_sub <- scp_sub[, scp_sub$SampleType == "Macrophage" & scp_sub$lcbatch == "LCB7"]
dim(scp_sub) # check dimensions
```

# NA effect in correlations (by Features)

```{r}
all_pNA <- DataFrame()

for (i in seq(from = 0.4, to = 0.9, by = 0.1)) {
  scp_NA <- filterNA(scp, i = "proteins_NA", pNA = i)

  df_NA <- assay(scp[["proteins"]])[rownames(scp_NA[["proteins_NA"]]), ]
  
  cor_df <- rcorr(t(df_NA[, ]), type = "pearson")
  
  diag(cor_df$r) <- NA
  diag(cor_df$P) <- NA
  
  cor_vals <- as.vector(cor_df$r)
  cor_vals <- cor_vals[!is.na(cor_vals)]
  
  p_vals <- as.vector(cor_df$P)
  p_vals <- p_vals[!is.na(p_vals)]
  
  df <- DataFrame(r = cor_vals,
                  p = p_vals,
                  pNA = rep.int(i, length(cor_vals)))
  
  all_pNA <- rbind(all_pNA, df)
}

all_pNA <- as.data.frame(all_pNA)
```

# Plot

```{r}
# Filter
filtered_all_pNA <- all_pNA

filtered_all_pNA <- all_pNA[all_pNA$p < 0.05, ]

# Violin plot
ggplot(filtered_all_pNA, aes(y = r, x = as.factor(pNA))) +
    geom_violin(position = "dodge", alpha = 0.5, outlier.colour = "transparent") +
    labs(x = "pNA Threshold", y = "Pearson Correlation") +
    theme_classic()
```

# NA effect in correlations (by Samples)

```{r}
# Missing Values
all_sNA <- DataFrame()

for (i in seq(from = 0.75, to = 0.83, by = 0.02)) {
  mtx <- assay(scp[["proteins_NA"]])
  
  # Proportion of missing values
  assay <- mtx[, colMeans(is.na(mtx)) < i]
  
  cor_df <- rcorr(assay, type = "pearson")

  diag(cor_df$r) <- NA
  diag(cor_df$P) <- NA
  
  cor_vals <- as.vector(cor_df$r)
  cor_vals <- cor_vals[!is.na(cor_vals)]
  
  p_vals <- as.vector(cor_df$P)
  p_vals <- p_vals[!is.na(p_vals)]
  
  df <- DataFrame(r = cor_vals,
                  p = p_vals,
                  sNA = rep.int(i, length(cor_vals)))
  
  all_sNA <- rbind(all_sNA, df)
}

all_sNA <- as.data.frame(all_sNA)
```

# Plot

```{r}
# Filter
filtered_all_sNA <- all_sNA

filtered_all_sNA <- all_sNA[all_sNA$p < 0.05, ]

# Violin plot
ggplot(filtered_all_sNA, aes(y = r, x = as.factor(sNA))) +
    geom_violin(position = "dodge", alpha = 0.5, outlier.colour = "transparent") +
    labs(x = "sNA Threshold", y = "Pearson Correlation") +
    theme_classic()
```

# Highly Variable Effect

```{r}
all_quantile <- DataFrame()

for (i in seq(from = 0.1, to = 0.6, by = 0.1)) {
  
  # Extract assay only
  df <- assay(scp[["proteins"]])
  
  # Highly Variable features
  var <- apply(df, 1, var)
  
  df <- df[var >= quantile(var, i), ]
  
  cor_df <- rcorr(t(df[, ]), type = "pearson")
  
  diag(cor_df$r) <- NA
  diag(cor_df$P) <- NA
  
  cor_vals <- as.vector(cor_df$r)
  cor_vals <- cor_vals[!is.na(cor_vals)]
  
  p_vals <- as.vector(cor_df$P)
  p_vals <- p_vals[!is.na(p_vals)]
  
  df <- DataFrame(r = cor_vals,
                  p = p_vals,
                  quant = rep.int(i, length(cor_vals)))
  
  all_quantile <- rbind(all_quantile, df)
}

all_quantile <- as.data.frame(all_quantile)
```

# Plot

```{r}
filtered_all_quantile <- all_quantile

filtered_all_quantile <- all_quantile[all_quantile$p < 0.05, ]

# Violin plot
ggplot(filtered_all_quantile, aes(y = r, x = as.factor(quant))) +
    geom_violin(position = "dodge", alpha = 0.5, outlier.colour = "transparent") +
    labs(x = "Most Variable Quantile", y = "Pearson Correlation") +
    theme_classic()
```