---
output: html_document
editor_options: 
chunk_output_type: console
---

# Install

```{r. eval = FALSE}
install.packages("textshape")
install.packages("pheatmap")
BiocManager::install("UniProt.ws")
install.packages("enrichR")
install.packages("dynamicTreeCut")
install.packages('WGCNA')
```

# Import

```{r}
library(textshape)
library(pheatmap)
library(UniProt.ws)
library(enrichR)
library(scp)
library(scpdata)
library(dynamicTreeCut)
library(Hmisc)
library(WGCNA)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(reshape2)
library(ggpubr)
```

# Load data

```{r}
# View(as.data.frame(scpdata())) # Available data sets
scp <- specht2019v3() # Load specific data set
```

# Cell Type

```{r}
# Subset same type of cells (cell type)
scp_sub <- getWithColData(scp, "proteins")
scp_macro <- scp_sub[, scp_sub$SampleType == "Macrophage"]
scp_mono <- scp_sub[, scp_sub$SampleType == "Monocyte"]

# Calculate correlations
cor_mono <- cor(t(assay(scp_mono)[, ]), method = "pearson")
cor_mono <- cluster_matrix(cor_mono, dim = "both", method = "average")

cor_macro <- cor(t(assay(scp_macro)[, ]), method = "pearson")
cor_macro <- cluster_matrix(cor_macro, dim = "both", method = "average")
```

# Identify Modules

```{r}
dist_mono <- 1 - cor_mono
dist_macro <- 1 - cor_macro

tree_mono <- hclust(as.dist(dist_mono), method = "average")
tree_macro <- hclust(as.dist(dist_macro), method = "average")

memberships_mono <- cutreeDynamic(tree_mono, distM = dist_mono, minClusterSize = 0)
memberships_macro <- cutreeDynamic(tree_macro, distM = dist_macro, minClusterSize = 0)
```

# Calculate Change in Modules

```{r}
diff_ls <- list()
for (i in unique(memberships_macro)) {
  cluster_mems <- rownames(cor_macro)[as.vector(memberships_macro) == i]
  temp_mono <- cor_mono[cluster_mems, cluster_mems]
  temp_macro <- cor_macro[cluster_mems, cluster_mems]
  diff <- temp_macro - temp_mono
  if (length(cluster_mems) > 10 & length(cluster_mems) < 30 & mean(abs(diff)) > 0 ) {
    diff_ls$diff[[i]] <- diff[upper.tri(diff)]
    diff_ls$n[[i]] <- length(cluster_mems)
  }
}
```

# Histogram

```{r}
df <- DataFrame()
for (i in seq(from = 1, to = length(diff_ls$diff), by = 1)) {
  if (!is.null(diff_ls$diff[[i]])) {
    temp_df <- as.data.frame(diff_ls$diff[[i]])
    colnames(temp_df) <- c("vals")
    temp_df$categ <- rep(i, length(temp_df$vals))
    df <- rbind(df, temp_df)
  }
}

ggplot(as.data.frame(df), aes(x = vals, fill = as.factor(categ))) +
    geom_density(alpha = 0.2, show_guide = FALSE)
```

# Plot

```{r}
for (i in 1:length(df$cluster)) {
  cluster_mems <- rownames(cor_macro)[memberships_macro == df$cluster[i]]
  
  # Plot the heat-maps
  temp <- cor_mono[cluster_mems, cluster_mems]
  melted_temp <- melt(temp)
  g1 <- ggplot(melted_temp, aes(x = Var1, y = Var2, fill = value)) + 
    geom_tile(show.legend = FALSE) + geom_text(aes(label = round(value, 2)),
                                               size = 2.1 - length(cluster_mems)/45) +
    scale_fill_gradient2(low = "#4d72af", mid = "white", high = "#c44e53",
                     midpoint = 0, breaks = seq(-1, 1, 0.25), limits = c(-1, 1)) + 
    theme(axis.text.y = element_text(angle = 0, hjust = 1, 
          size = 8 - length(cluster_mems)/45), axis.text.x = element_blank(),
          axis.ticks.x = element_blank(), axis.title.x = element_blank(), 
          axis.title.y = element_blank()) +
    labs(title = "Monocyte")
  
  temp <- cor_macro[cluster_mems, cluster_mems]
  melted_temp <- melt(temp)
  g2 <- ggplot(melted_temp, aes(x = Var1, y = Var2, fill = value)) + 
    geom_tile(show.legend = FALSE) + geom_text(aes(label = round(value, 2)),
                                               size = 2.1 - length(cluster_mems)/45) +
    scale_fill_gradient2(low = "#4d72af", mid = "white", high = "#c44e53",
                     midpoint = 0, breaks = seq(-1, 1, 0.25), limits = c(-1, 1)) + 
    theme(axis.text.y = element_blank(),axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(), axis.title.x = element_blank(), 
          axis.title.y = element_blank())+
    labs(title = "Macrophage")
  
  g3 <- ggarrange(g1, g2, width = 50, height = 40)
  ggsave(paste0("~/WGCNA-Practice/output/diffUns/", i, ".pdf"))
}
```
