---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Import packages

```{r}
library(textshape)
library(Hmisc)
library(scp)
library(scpdata)
library(dplyr)
library(ggplot2)
library(tidyr)
library(pheatmap)
```

# Load data

```{r}
# View(as.data.frame(scpdata())) # Available data sets
scp <- specht2019v3() # Load data
```

# Within peptides of a same protein

```{r}
df <- as.data.frame(rowData(scp[["peptides"]]))

peptide_assay <- assay(scp[["peptides"]])

all_cor_df <- DataFrame()

for (protein in rownames(assay(scp[["proteins"]]))) {
  
  peptides <- as.vector(df[, "peptide"][df[, "protein"] == protein])
  sub_pep_assay <- peptide_assay[peptides, ]
  
  if (length(peptides) >= 2) {
    res <- rcorr(t(sub_pep_assay), type = "pearson")
    ind <- which(upper.tri(res$r), arr.ind = TRUE)
    nn <- dimnames(res$r)
    temp_df <- data.frame(protein = rep(protein, length(ind)),
                          peptide1 = nn[[1]][ind[, 1]],
                          peptide2 = nn[[2]][ind[, 2]],
                          r = res$r[ind],
                          p = res$P[ind])
    all_cor_df <- rbind(all_cor_df, temp_df)
  }
}

# Clean dataframe
all_cor_df <- all_cor_df[!duplicated(all_cor_df), ]
all_cor_df <- all_cor_df[!is.na(all_cor_df[c(5)]), ]
all_cor_df <- all_cor_df[all_cor_df$p != 0, ]

# all_cor_df$adj_p <- p.adjust(all_cor_df$p, method = "BH")
all_cor_df <- all_cor_df[all_cor_df$p <= 0.05, ]
all_cor_df <- as.data.frame(all_cor_df)
```

# Plot

```{r}
ggplot() + aes(all_cor_df$r)+ geom_histogram(binwidth = 0.1,
                                        colour = "black", fill = "white") +
  ylim(0, 3500)

View(all_cor_df)
```

# Functions to identify anti-correlated peptides

```{r}
listPos <- function(df, neg = FALSE) {
  all_peps <- unique(c(df$peptide1, df$peptide2))
  res <- c()
  for (pep in all_peps) {
    if (neg == TRUE) {
      if (all(df[(df$peptide1 == pep) | (df$peptide2 == pep), ]$r < 0)) {
      res <- c(res, pep)
      
      }
    } else {
      if (all(df[(df$peptide1 == pep) | (df$peptide2 == pep), ]$r > 0)) {
      res <- c(res, pep)
      }
    }
  }
  return (res)
}
```

# Filter anti-correlated

```{r}
# Identify anti-correlated peptides
to_be_removed <- c()

for (protein in unique(all_cor_df$protein)) {
    # All peps of a protein
    sub_all <- all_cor_df[all_cor_df$protein == protein, ]
    
    ### Peptides having only positive correlation ###
    pos_peptides <- listPos(sub_all)

    # Extend these peptides with their correlation partners
    sub_pos <- subset(sub_all, (peptide1 %in% pos_peptides) |
                               (peptide2 %in% pos_peptides))
    pos_peptides <- unique(c(sub_pos$peptide1, sub_pos$peptide2))
    
    
    ### Peptides having only negative correlation ###
    neg_peptides <- listPos(sub_all, neg = TRUE)
    
    to_be_removed <- c(to_be_removed, neg_peptides)
    
    # Extend these peptides with their correlation partners
    sub_neg <- subset(sub_all, (peptide1 %in% neg_peptides) |
                               (peptide2 %in% neg_peptides))
    
    # Correlation partners of neg_peptides should be pos_peptides
    neg_peptides2 <- unique(c(sub_neg$peptide1, sub_neg$peptide2))
    pos_peptides <- c(pos_peptides, setdiff(neg_peptides2, neg_peptides))
    
    # Extend further with all possible
    for (i in 1:5) {
      sub_pos <- subset(sub_all, ((peptide1 %in% pos_peptides) | (peptide2 %in% pos_peptides)) & r > 0)
    
      pos_peptides <- unique(c(pos_peptides, c(sub_pos$peptide1, sub_pos$peptide2)))
    }
    
    # Determine peptides can be removed
    sub_all <- subset(sub_all, (peptide1 %in% pos_peptides) |
                               (peptide2 %in% pos_peptides))
    
    suspects <- unique(c(sub_all[sub_all$r < 0, ]$peptide1, 
                         sub_all[sub_all$r < 0, ]$peptide2))
    
    to_be_removed <- c(to_be_removed, setdiff(suspects, pos_peptides))
}
to_be_removed <- unique(to_be_removed)
```

# Plot removed peptides

```{r}
length(to_be_removed)

all_cleaned <- subset(all_cor_df, !((peptide1 %in% to_be_removed) |
                               (peptide2 %in% to_be_removed)))

# Histogram of removed peptides' correlations
ggplot() + aes(setdiff(all_cor_df, all_cleaned)$r)+ geom_histogram(binwidth = 0.1,
                                        colour = "black", fill = "white") +
  ylim(0, 200)
```

# Correlation change after removing anti-correlated peptides

```{r}
# Aggregate with all peptides
scp <- aggregateFeaturesOverAssays(scp, i = "peptides", fcol = "protein", 
                                    name = "proteins_w_all", fun = colMeans)

# Filter the anti-correlated peptides
scp[["filtered_peptides"]] <- scp[["peptides"]][!(rowData(scp[["peptides"]])$peptide %in% to_be_removed), ]

# Aggregate with filtered peptides
scp <- aggregateFeaturesOverAssays(scp, i = "filtered_peptides", fcol = "protein", 
                                    name = "proteins_w_filtered", fun = colMeans)

# Aggregate with random peptides
random_removed <- sample(rowData(scp[["peptides"]])$peptide, length(unique(to_be_removed))) 

# Filter some random peptides
scp[["random_peptides"]] <- scp[["peptides"]][!(rowData(scp[["peptides"]])$peptide %in% random_removed), ]

# Aggregate with random peptides
scp <- aggregateFeaturesOverAssays(scp, i = "random_peptides", fcol = "protein", 
                                    name = "proteins_w_random", fun = colMeans)

# Calculate correlations
res <- rcorr(t(assay(scp[["proteins_w_all"]])), type = "pearson")
cor_all <- res$r
p_all <- res$P
diag(cor_all) <- NA

res <- rcorr(t(assay(scp[["proteins_w_filtered"]])), type = "pearson")
cor_filtered <- res$r
p_filtered <- res$P
diag(cor_filtered) <- NA

res <- rcorr(t(assay(scp[["proteins_w_random"]])), type = "pearson")
cor_random <- res$r
p_random <- res$P
diag(cor_random) <- NA

# Remove NA in correlations and create dataframe for plotting
all_df <- data.frame(r = cor_all[!is.na(cor_all)],
                     type = rep("All Peptides", length(cor_all[!is.na(cor_all)])))

filtered_df <- data.frame(r = cor_filtered[!is.na(cor_filtered)],
                     type = rep("Filtered Peptides", length(cor_filtered[!is.na(cor_filtered)])))

random_df <- data.frame(r = cor_random[!is.na(cor_random)],
                     type = rep("Random Peptides", length(cor_random[!is.na(cor_random)])))

dim(random_df)
dim(all_df)
dim(filtered_df)

dim(cor_filtered)
dim(cor_all)
dim(cor_random)


# ggplot(rbind(all_df, filtered_df), aes(y = r, x = as.factor((type)))) + 
#     geom_boxplot() +
#     geom_jitter(color = "black", size = 0.01, alpha = 0.3) +
#     theme_classic()
```

# Check protein correlations

```{r}
# Determine the altered proteins through peptides
prots_altered <- unique(rowData(scp[["peptides"]][rowData(scp[["peptides"]])$peptide %in% to_be_removed, ])$protein)

# Match dimensions (filtered having less features)
cor_all <- cor_all[rownames(cor_all) %in% rownames(cor_filtered), 
                   colnames(cor_all) %in% colnames(cor_filtered) ]

logics <- (is.na(cor_all) & !is.na(cor_filtered)) & (p_filtered < 0.01)

aa <- DataFrame()

dim(logics)

ind <- which(upper.tri(logics), arr.ind = TRUE)

rownames(logics)["A0A0B4J1V0":rownames(logics)[length(rownames(logics))]]

for (index in seq(from = 1, to = 4579851, by = 1)) {
  if (!is.na(logics[ind[index, ][["row"]], ind[index, ][["col"]]])) {
    if (logics[ind[index, ][["row"]], ind[index, ][["col"]]] == TRUE) {
      print(logics[ind[index, ][["row"]], ind[index, ][["col"]]])
    }
  }
}

plot(x = assay(scp[["proteins_w_filtered"]])["O60888", ], 
     y = assay(scp[["proteins_w_filtered"]])["Q8NHP7", ])

plot(x = assay(scp[["proteins_w_all"]])["O60888", ], 
     y = assay(scp[["proteins_w_all"]])["Q8NHP7", ])
```

# Alternative anti-correlated peptide detection

```{r}
# Identify anti-correlated peptides
to_be_removed <- c()

for (protein in unique(all_cor_df$protein)) {
    # All peps of a protein
    sub_all <- all_cor_df[all_cor_df$protein == protein, ]
    
    sub_neg <- sub_all[sub_all$r < 0, ]
    
    all_neg <- c(sub_neg$peptide1, sub_neg$peptide2)
    
    while (length(all_neg) > 0) {
      most_connected <- sort(table(all_neg), decreasing = TRUE)[1]
      most_connected <- names(most_connected)[1]
      to_be_removed <- c(to_be_removed, most_connected)
      sub_neg <- sub_neg[!(sub_neg$peptide1 == most_connected |
                           sub_neg$peptide2 == most_connected), ]
      
      all_neg <- c(sub_neg$peptide1, sub_neg$peptide2)
    }
}

```

