---
output: html_document
editor_options: 
chunk_output_type: console
---

# Install

```{r. eval = FALSE}
install.packages("textshape")
install.packages("pheatmap")
BiocManager::install("UniProt.ws")
install.packages("enrichR")
install.packages("dynamicTreeCut")
```

# Import

```{r}
library(textshape)
library(pheatmap)
library(UniProt.ws)
library(enrichR)
library(scp)
library(scpdata)
library(dynamicTreeCut)
library(Hmisc)
```

# Load data

```{r}
# View(as.data.frame(scpdata())) # Available data sets
scp <- specht2019v3() # Load specific data set
```

# Cell Type + Batch

```{r}
# Subset same type of cells (cell type + batch)
scp_sub <- getWithColData(scp, "proteins")
scp_sub <- scp_sub[, scp_sub$SampleType == "Macrophage" & scp_sub$lcbatch == "LCB7"]
dim(scp_sub) # check dimensions

# Extract assay only
df_CPM <- assay(scp_sub)

# Calculate correlations
cor_df <- cor(t(df_CPM[, ]), method = "pearson")
```

# Variable Features

```{r}
# Extract assay only
df_CPM <- assay(scp[["proteins"]])

# Highly Variable features
var <- apply(df_CPM, 1, var)

# Most variable 50%
df_CPM <- df_CPM[var >= quantile(var, 0.5), ]

# Least variable 50%
df_CPM <- df_CPM[var < quantile(var, 0.5), ]

# Check dimensions
dim(df_CPM)

# Calculate correlations
cor_df <- cor(t(df_CPM[, ]), method = "pearson")
```

# Missing Values

```{r}
# Missing Values
scp <- aggregateFeaturesOverAssays(scp, i = "peptides", fcol = "protein", 
                                    name = "proteins_NA", fun = colMedians)

# more than 99.99% missing
scp_NA <- filterNA(scp, i = "proteins_NA", pNA = 0.9999)

prots <- setdiff(rownames(assay(scp[["proteins"]])), rownames(scp_NA[["proteins_NA"]]))
length(prots)
df_CPM <- assay(scp[["proteins"]])[prots, ]

# Less than 96.5% missing
scp_NA <- filterNA(scp, i = "proteins_NA", pNA = 0.965)
prots <- rownames(scp_NA[["proteins_NA"]])
length(prots)
df_CPM <- assay(scp[["proteins"]])[prots, ]

# Calculate correlations
cor_df <- cor(t(df_CPM[, ]), method = "pearson")
```

# Order based on correlations

```{r}
# Cluster and order the data frame
ordered_cor_df <- cluster_matrix(cor_df, dim = "both", method = "average")

diag(ordered_cor_df) <- 0

# Plot the heat-map
temp <- ordered_cor_df
pheatmap(temp,
         color = colorRampPalette(c("#4d72af", "white", "#c44e53")) (101),
         breaks = seq(from = -1, to = 1, length.out = 101),
         border_color = NA,legend = FALSE, show_colnames = FALSE,
         show_rownames = FALSE,
         cluster_rows = FALSE, cluster_cols = FALSE,
         cellwidth = 450/nrow(temp), cellheight = 450/nrow(temp))
```

# Identify Clusters

```{r}
distance_df <- 1 - cor_df

tree <- hclust(as.dist(distance_df), method = "average")

memberships_CPM <- cutreeDynamic(tree, distM = distance_df, minClusterSize = 15)

memberships_CPM <- as.data.frame(memberships_CPM)
```

# Cluster Enrichments

```{r}
# Choose a cluster
table(memberships_CPM)

cluster_members_CPM <- rownames(cor_df)[memberships_CPM$memberships_CPM == 4]
length(cluster_members_CPM)

# Map to Gene names
up <- UniProt.ws(taxId = 9606)
res <- AnnotationDbi::select(
    x = up,
    keys = cluster_members_CPM,
    to = "Gene_Name"
)

# List of databases: View(listEnrichrDbs())
dbs <- c("WikiPathway_2023_Human", "GO_Molecular_Function_2023", "KEGG_2021_Human")
enriched_CPM <- enrichr(res$To, dbs)
plotEnrich(enriched_CPM[[3]], showTerms = 10,
           numChar = 40, y = "Ratio", orderBy = "P.value")
```

# Analyze Clusters

```{r}
enrichment <- 1
enriched_genes <- strsplit(enriched_CPM[[3]][enrichment, "Genes"], ";")[[1]]

# View(enriched_WGCNA[[3]])
enriched_genes
enriched_prots <- c()
for (i in 1:length(res$To)) {
  if (res$To[i] %in% enriched_genes) {
    enriched_prots <- c(enriched_prots,(res$From[i]))
  }
}

temp_df <- cor_df[enriched_prots, enriched_prots]
pheatmap(temp_df,
         color = colorRampPalette(c("#4d72af", "white", "#c44e53")) (101),
         breaks = seq(from = -1, to = 1, length.out = 101),
         border_color = NA,legend = FALSE, show_colnames = FALSE,
         show_rownames = TRUE,
         cluster_rows = FALSE, cluster_cols = FALSE,
         cellwidth = 550/nrow(temp_df), cellheight = 550/nrow(temp_df),
         fontfamily = 'sans', fontsize = 10,
         display_numbers = round(temp_df, 2))
```

