---
output: html_document
editor_options: 
chunk_output_type: console
---

# Install

```{r. eval = FALSE}
install.packages('WGCNA')
BiocManager::install("UniProt.ws")
install.packages("enrichR")
```

# Import

```{r}
library(WGCNA)
library(scp)
library(scpdata)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(UniProt.ws)
library(enrichR)
library(pheatmap)
library(Hmisc)
```

# Load data

```{r}
# View(as.data.frame(scpdata())) # Available data sets
scp <- specht2019v3() # Load specific data set
```

# Cell Type + Batch

```{r}
# Subset same type of cells (cell type + batch)
scp_sub <- getWithColData(scp, "proteins")
scp_sub <- scp_sub[, scp_sub$SampleType == "Macrophage" & scp_sub$lcbatch == "LCB7"]
dim(scp_sub) # check dimensions

# Extract assay only
df_WGCNA <- assay(scp_sub)

# Calculate correlations
cor_df <- cor(t(df_WGCNA[, ]), method = "pearson")
```

# Variable Features

```{r}
# Extract assay only
df_WGCNA <- assay(scp[["proteins"]])

# Highly Variable features
var <- apply(df_WGCNA, 1, var)

# Most variable 50%
df_WGCNA <- df_WGCNA[var >= quantile(var, 0.5), ]

# Least variable 50%
df_WGCNA <- df_WGCNA[var < quantile(var, 0.5), ]

# Check dimensions
dim(df_WGCNA)

# Calculate correlations
cor_df <- cor(t(df_WGCNA[, ]), method = "pearson")
```

# Missing Values

```{r}
# Missing Values
scp <- aggregateFeaturesOverAssays(scp, i = "peptides", fcol = "protein", 
                                    name = "proteins_NA", fun = colMedians)

# more than 99.99% missing
scp_NA <- filterNA(scp, i = "proteins_NA", pNA = 0.9999)

prots <- setdiff(rownames(assay(scp[["proteins"]])), rownames(scp_NA[["proteins_NA"]]))
length(prots)
df_WGCNA <- assay(scp[["proteins"]])[prots, ]

# Less than 96.5% missing
scp_NA <- filterNA(scp, i = "proteins_NA", pNA = 0.965)
prots <- rownames(scp_NA[["proteins_NA"]])
length(prots)
df_WGCNA <- assay(scp[["proteins"]])[prots, ]

# Calculate correlations
cor_df <- cor(t(df_WGCNA[, ]), method = "pearson")
```

# Module detection

```{r}
temp_cor <- cor
cor <- WGCNA::cor

TOM <- TOMsimilarity(cor_df, TOMType = "signed")

dissTOM <- 1 - TOM

# Generate a clustered gene tree
geneTree <- hclust(as.dist(dissTOM), method = "average")

#This sets the minimum number of genes to cluster into a module
dynamicMods <- cutreeDynamic(geneTree, minClusterSize = 15)

plotDendroAndColors(geneTree, labels2colors(dynamicMods),
                    c("Dynamic Tree Cut"),
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)

clusters_WGCNA <- as.data.frame(dynamicMods)
```

# Cluster Enrichment

```{r}
table(clusters_WGCNA) # All clusters
cluster_members_WGCNA <- rownames(df_WGCNA)[clusters_WGCNA == 1]

# Map to Gene names
up <- UniProt.ws(taxId = 9606)

res <- AnnotationDbi::select(
    x = up,
    keys = cluster_members_WGCNA,
    to = "Gene_Name"
)

# List of databases: View(listEnrichrDbs())
dbs <- c("WikiPathway_2023_Human", "GO_Molecular_Function_2023", "KEGG_2021_Human")
enriched_WGCNA <- enrichr(res$To, dbs)
plotEnrich(enriched_WGCNA[[3]], showTerms = 10, numChar = 40, y = "Ratio")
```

# Visualize Clusters

```{r}
enrichment <- 1
enriched_genes <- strsplit(enriched_WGCNA[[3]][enrichment, "Genes"], ";")[[1]]

# View(enriched_WGCNA[[3]])
enriched_genes
enriched_prots <- c()
for (i in 1:length(res$To)) {
  if (res$To[i] %in% enriched_genes) {
    enriched_prots <- c(enriched_prots,(res$From[i]))
  }
}

temp_df <- cor_df[enriched_prots, enriched_prots]
pheatmap(temp_df,
         color = colorRampPalette(c("#4d72af", "white", "#c44e53")) (101),
         breaks = seq(from = -1, to = 1, length.out = 101),
         border_color = NA,legend = FALSE, show_colnames = FALSE,
         show_rownames = TRUE,
         cluster_rows = FALSE, cluster_cols = FALSE,
         cellwidth = 550/nrow(temp_df), cellheight = 550/nrow(temp_df),
         fontfamily = 'sans', fontsize = 10,
         display_numbers = round(temp_df, 2))
```

