---
output: html_document
editor_options: 
chunk_output_type: console
---

# Install

```{r. eval = FALSE}
install.packages("textshape")
install.packages("pheatmap")
BiocManager::install("UniProt.ws")
install.packages("enrichR")
install.packages("dynamicTreeCut")
```

# Import

```{r}
library(textshape)
library(pheatmap)
library(UniProt.ws)
library(enrichR)
library(scp)
library(scpdata)
library(dynamicTreeCut)
library(Hmisc)
```

# Load data

```{r}
# View(as.data.frame(scpdata())) # Available data sets

scp <- specht2019v3() # Load specific data set

# Subset same type of cells
scp_sub <- getWithColData(scp, "proteins")
# scp_sub <- scp_sub[, scp_sub$SampleType == "Macrophage" & scp_sub$lcbatch == "LCB7"]
# dim(scp_sub) # check dimensions

# Extract assay only
df_CPM <- assay(scp_sub)

# Highly Variable features
var <- apply(df_CPM, 1, var)
df_CPM <- df_CPM[var >= quantile(var, 0.5), ]
dim(df_CPM)

corr <- rcorr(t(df_CPM[, ]), type = "pearson")
cor_df <- corr$r

# cor_df[corr$P > 0.05 & abs(corr$r) > 0.3] <- 0
# Explore
# hist(df_CPM[, 3])
# apply(df_CPM, 1, hist)
```

# Calculate correlations

```{r}
# Cluster and order the data frame
ordered_cor_df <- cluster_matrix(cor_df, dim = "both", method = "average")

# Plot the heat-map
temp <- ordered_cor_df[15:20, 15:20]
pheatmap(temp,
         color = colorRampPalette(c("#4d72af", "white", "#c44e53")) (101),
         breaks = seq(from = -1, to = 1, length.out = 101),
         border_color = NA,legend = FALSE, show_colnames = FALSE,
         show_rownames = FALSE,
         cluster_rows = FALSE, cluster_cols = FALSE,
         cellwidth = 400/nrow(temp), cellheight = 400/nrow(temp),
         display_numbers = round(temp, 2))
```

# Identify Clusters

```{r}
distance_df <- 1 - cor_df

tree <- hclust(as.dist(distance_df), method = "average")

memberships_CPM <- cutreeDynamic(tree, distM = distance_df, minClusterSize = 15)

memberships_CPM <- as.data.frame(memberships_CPM)
```
# Cluster Selection

```{r}
# Choose a cluster

table(memberships_CPM)

cluster_members_CPM <- rownames(cor_df)[memberships_CPM$memberships_CPM == 1]
length(cluster_members_CPM)

# Map to Gene names
up <- UniProt.ws(taxId = 9606)
res <- select(
    x = up,
    keys = cluster_members_CPM,
    to = "Gene_Name"
)

# # Subplot of module correlation
# temp_df <- ordered_cor_df[cluster_members_CPM, cluster_members_CPM]
# if (length(res$To) == length(rownames(temp_df))){
#   rownames(temp_df) <- res$To 
#   colnames(temp_df) <- res$To 
# }
# pheatmap(temp_df,
#          color = colorRampPalette(c("#4d72af", "white", "#c44e53")) (101),
#          breaks = seq(from = -1, to = 1, length.out = 101),
#          border_color = NA,legend = FALSE, show_colnames = TRUE, 
#          show_rownames = TRUE,
#          cluster_rows = FALSE, cluster_cols = FALSE,
#          cellwidth = 500/nrow(temp_df), cellheight = 500/nrow(temp_df),
#          fontfamily = 'sans', fontsize = 10,
#          display_numbers = round(temp_df, 2))
```

# Enrichments

```{r}
# List of databases: View(listEnrichrDbs())

# View(listEnrichrDbs())

dbs <- c("WikiPathway_2023_Human", "GO_Molecular_Function_2023", "KEGG_2021_Human")
enriched <- enrichr(res$To, dbs)
plotEnrich(enriched[[3]], showTerms = 10,
           numChar = 40, y = "Ratio", orderBy = "P.value")
```


