---
output: html_document
editor_options: 
  chunk_output_type: console
---

# https://wikis.utexas.edu/display/bioiteam/Clustering+using+WGCNA


# Install

```{r. eval = FALSE}

```

# Import

```{r}
library(WGCNA)
library(gridExtra)
library(ggplot2)
```

# Load Data

```{r}
load("SamplesAndTraits.RData") # Prepared data

# Explore
View(datExpr)
View(datTraits)
apply(datExpr, 1, hist)
```

# Soft threshold

```{r}
powers <- c(c(1:10), seq(from = 10, to = 30, by = 1))
sft <- pickSoftThreshold(datExpr, powerVector = powers, 
                        verbose = 5, networkType = "signed") 

sizeGrWindow(9, 5)
par(mfrow = c(1, 2))
cex1 <- 0.9

plot(sft$fitIndices[, 1], -sign(sft$fitIndices[, 3])*sft$fitIndices[, 2],
     xlab = "Soft Threshold (power)", 
     ylab = "Scale Free Topology Model Fit, signed R^2", 
     type = "n", main = paste("Scale independence"))

text(sft$fitIndices[,1], -sign(sft$fitIndices[, 3])*sft$fitIndices[, 2], 
     labels = powers, cex = cex1, col = "red")

abline(h = 0.90, col = "red")
plot(sft$fitIndices[, 1], sft$fitIndices[, 5], 
     xlab = "Soft Threshold (power)", ylab = "Mean Connectivity", 
     type = "n", main = paste("Mean connectivity"))

text(sft$fitIndices[, 1], sft$fitIndices[, 5], 
     labels = powers, cex = cex1, col = "red")
 

```

# Construct a gene co-expression matrix, TOM, distance TOMM

```{r}
#build a adjacency "correlation" matrix
enableWGCNAThreads()
adjacency <- adjacency(datExpr, power = sft$powerEstimate, type = "signed") #specify network type
head(adjacency)

TOM <- TOMsimilarity(adjacency, TOMType = "signed") # specify network type

dissTOM <- 1 - TOM

```

# Generate Modules

```{r}
# Generate a clustered gene tree
geneTree <- hclust(as.dist(dissTOM), method = "average")


plot(geneTree, xlab = "", sub = "",
     main = "Gene Clustering on TOM-based dissimilarity", 
     labels = FALSE, hang = 0.04)

#This sets the minimum number of genes to cluster into a module
dynamicMods <- cutreeDynamic(dendro = geneTree, distM = dissTOM, deepSplit = 2,
                            pamRespectsDendro= FALSE, minClusterSize = 30)
dynamicColors <- labels2colors(dynamicMods)

MEList = moduleEigengenes(datExpr, colors = dynamicColors, 
                          softPower = sft$powerEstimate)
MEs <- MEList$eigengenes

MEDiss <- 1 - cor(MEs)
METree <- hclust(as.dist(MEDiss), method = "average")

save(dynamicMods, MEList, MEs, MEDiss, METree, 
     file = "Network_allSamples_signed_RLDfiltered.RData")

plot(METree, main = "Clustering of module eigengenes", xlab = "", sub = "")

MEDissThres <- 0.0
merge <- mergeCloseModules(datExpr, dynamicColors, cutHeight = MEDissThres,
                           verbose = 3)
mergedColors <- merge$colors
mergedMEs <- merge$newMEs

plotDendroAndColors(geneTree, cbind(dynamicColors, mergedColors), 
                    c("Dynamic Tree Cut", "Merged dynamic"),
                    dendroLabels = FALSE, hang = 0.03, 
                    addGuide = TRUE, guideHang = 0.05)

moduleColors <- mergedColors
colorOrder <- c("grey", standardColors(50))
moduleLabels <- match(moduleColors, colorOrder) - 1
MEs <- mergedMEs

save(MEs, moduleLabels, moduleColors, geneTree,
     file = "Network_allSamples_signed_nomerge_RLDfiltered.RData")
```

# Relate gene expression modules to traits

```{r}
# Define number of genes and samples
nGenes <- ncol(datExpr)
nSamples  <- nrow(datExpr)

# Recalculate MEs with color labels
MEs0 <- moduleEigengenes(datExpr, moduleColors)$eigengenes
MEs <- orderMEs(MEs0)
moduleTraitCor <- cor(MEs, datTraits, use = "p")
moduleTraitPvalue <- corPvalueStudent(moduleTraitCor, nSamples)
 
# Print correlation heatmap between modules and traits
textMatrix <- paste(signif(moduleTraitCor, 2), "\n(",
                        signif(moduleTraitPvalue, 1), ")", sep = "")
dim(textMatrix) <- dim(moduleTraitCor)
par(mar <- c(6, 8.5, 3, 3))
 
# display the corelation values with a heatmap plot
# INCLUE THE NEXT LINE TO SAVE TO FILE
# pdf(file="heatmap.pdf")
labeledHeatmap(Matrix = moduleTraitCor,
            xLabels = names(datTraits),
            yLabels = names(MEs),
            ySymbols = names(MEs),
            colorLabels = FALSE,
            colors = blueWhiteRed(50),
            textMatrix = textMatrix,
            setStdMargins = FALSE,
            cex.text = 0.5,
            zlim = c(-1, 1),
            main = paste("Module-trait relationships"))

names(datExpr)[moduleColors == "brown"]
```


